apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f compose.yaml -f compose.dev.yaml convert -c
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: isopenapi
  name: isopenapi
spec:
  ports:
    - name: "4700"
      port: 4700
      targetPort: 8080
  selector:
    io.kompose.service: isopenapi
