{{/*
Traefik IngressRouteTCP resources for X-Road Security Server
This template is included conditionally from security-server.yaml
*/}}
{{- define "x-road-ss.traefik.ingress" -}}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "x-road-ss.fullnameWithId" . }}-tcp-5500
spec:
  entryPoints:
    - xrd5500
  routes:
    - match: HostSNI(`{{ include "x-road-ss.fqdn" . }}`)
      services:
        - name: {{ include "x-road-ss.fullnameWithId" . }}
          port: 5500
  tls:
    passthrough: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "x-road-ss.fullnameWithId" . }}-http-5577
spec:
  entryPoints:
    - xrd5577
  routes:
    - match: HostSNI(`{{ include "x-road-ss.fqdn" . }}`)
      services:
        - name: {{ include "x-road-ss.fullnameWithId" . }}
          port: 5577
  tls:
    passthrough: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "x-road-ss.fullnameWithId" . }}-http-5588
spec:
  entryPoints:
    - xrd5588
  routes:
    - match: HostSNI(`{{ include "x-road-ss.fqdn" . }}`)
      services:
        - name: {{ include "x-road-ss.fullnameWithId" . }}
          port: 5588
  tls:
    passthrough: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "x-road-ss.fullnameWithId" . }}-http-8080
spec:
  entryPoints:
    - xrd8080
  routes:
    - match: HostSNI(`{{ include "x-road-ss.fqdn" . }}`)
      services:
        - name: {{ include "x-road-ss.fullnameWithId" . }}
          port: 8080
  tls:
    passthrough: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "x-road-ss.fullnameWithId" . }}-tcp-8443
spec:
  entryPoints:
    - xrd8443
  routes:
    - match: HostSNI(`{{ include "x-road-ss.fqdn" . }}`)
      services:
        - name: {{ include "x-road-ss.fullnameWithId" . }}
          port: 8443
  tls:
    passthrough: true
{{- end -}}

