---
# CA OCSP Service Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "x-road-test-ca.fullnameWithId" $ }}-ocsp-ingress
  labels:
    {{- include "x-road-test-ca.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # Use cert-manager to automatically obtain Let's Encrypt certificate
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ocsp.im.assembly.govstack.global
      secretName: {{ include "x-road-test-ca.fullnameWithId" $ }}-ocsp-tls
  rules:
    - host: ocsp.im.assembly.govstack.global
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "x-road-test-ca.fullnameWithId" $ }}
                port:
                  number: 8888
---
# CA ACME Service Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "x-road-test-ca.fullnameWithId" $ }}-acme-ingress
  labels:
    {{- include "x-road-test-ca.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # Use cert-manager to automatically obtain Let's Encrypt certificate
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - acme.im.assembly.govstack.global
      secretName: {{ include "x-road-test-ca.fullnameWithId" $ }}-acme-tls
  rules:
    - host: acme.im.assembly.govstack.global
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "x-road-test-ca.fullnameWithId" $ }}
                port:
                  number: 8887
---
# CA TSA Service Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "x-road-test-ca.fullnameWithId" $ }}-tsa-ingress
  labels:
    {{- include "x-road-test-ca.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # Use cert-manager to automatically obtain Let's Encrypt certificate
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tsa.im.assembly.govstack.global
      secretName: {{ include "x-road-test-ca.fullnameWithId" $ }}-tsa-tls
  rules:
    - host: tsa.im.assembly.govstack.global
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "x-road-test-ca.fullnameWithId" $ }}
                port:
                  number: 8899